-- MySQL Script generated by MySQL Workbench
-- sex 17 ago 2018 10:58:35 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering





CREATE TABLE  "states" (
  "id" VARCHAR(2) NOT NULL,
  "name" VARCHAR(100) NULL,
  PRIMARY KEY ("id"));


-- -----------------------------------------------------
-- Table "citys"
-- -----------------------------------------------------


CREATE TABLE  "citys" (
  "id" INT NOT NULL ,
  "name" VARCHAR(100) NULL,
  "state_id" VARCHAR(2) NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_citys_states1"
    FOREIGN KEY ("state_id")
    REFERENCES "states" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "addresses"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "addresses" CASCADE;

CREATE TABLE  "addresses" (
  "id" INT NOT NULL,
  "street" VARCHAR(200) NULL,
  "cep" VARCHAR(9) NULL,
  "hint" VARCHAR(200) NULL,
  "city_id" INT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_addresses_citys1"
    FOREIGN KEY ("city_id")
    REFERENCES "citys" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "users"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "users" CASCADE;

CREATE TABLE  "users" (
  "id" INT NOT NULL,
  "name" VARCHAR(200) NULL,
  "password" VARCHAR(20) NULL,
  "email" VARCHAR(200) NULL,
  "type" CHAR NULL,
  "cpf" VARCHAR(15) NULL,
  "address_id" INT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_users_addresses1"
    FOREIGN KEY ("address_id")
    REFERENCES "addresses" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "phones"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "phones" CASCADE;

CREATE TABLE  "phones" (
  "id" INT NOT NULL ,
  "user_id" INT NOT NULL,
  "phone" VARCHAR(20) NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_phones_usuario"
    FOREIGN KEY ("user_id")
    REFERENCES "users" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "categories"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "categories" CASCADE;

CREATE TABLE  "categories" (
  "id" INT NOT NULL ,
  "name" VARCHAR(45) NULL,
  "description" VARCHAR(200) NULL,
  PRIMARY KEY ("id"));


-- -----------------------------------------------------
-- Table "products"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "products" CASCADE;

CREATE TABLE  "products" (
  "id" INT NOT NULL,
  "description" VARCHAR(200) NULL,
  "name" VARCHAR(100) NULL,
  "price" DECIMAL NULL,
  "category_id" INT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_products_category1"
    FOREIGN KEY ("category_id")
    REFERENCES "categories" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "images"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "images" CASCADE;

CREATE TABLE  "images" (
  "id" INT NOT NULL,
  "name" VARCHAR(45) NULL,
  "label" VARCHAR(200) NULL,
  "product_id" INT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_images_products1"
    FOREIGN KEY ("product_id")
    REFERENCES "products" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "orders"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "orders" CASCADE;

CREATE TABLE  "orders" (
  "id" INT NOT NULL ,
  "users_id" INT NOT NULL,
  "products_id" INT NOT NULL,
  PRIMARY KEY ("id", "users_id", "products_id"),
  CONSTRAINT "fk_users_has_products_users1"
    FOREIGN KEY ("users_id")
    REFERENCES "users" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_users_has_products_products1"
    FOREIGN KEY ("products_id")
    REFERENCES "products" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "entry"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "entry" CASCADE;

CREATE TABLE  "entry" (
  "id" INT NOT NULL,
  "note_number" INT NULL,
  "description" VARCHAR(200) NULL,
  "user_id" INT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_entry_users1"
    FOREIGN KEY ("user_id")
    REFERENCES "users" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "movimentations"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "movimentations" CASCADE;

CREATE TABLE  "movimentations" (
  "id" INT NOT NULL ,
  "entry_id" INT NOT NULL,
  "products_id" INT NOT NULL,
  "quantity" VARCHAR(45) NULL,
  "price_paid" DECIMAL NULL,
  PRIMARY KEY ("id", "entry_id", "products_id"),
  CONSTRAINT "fk_entry_has_products_entry1"
    FOREIGN KEY ("entry_id")
    REFERENCES "entry" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_entry_has_products_products1"
    FOREIGN KEY ("products_id")
    REFERENCES "products" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


DROP SEQUENCE IF EXISTS "citys_id_sequence";
CREATE SEQUENCE  "citys_id_sequence";
ALTER TABLE "citys" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"citys_id_sequence"');
DROP SEQUENCE IF EXISTS "phones_id_sequence";
CREATE SEQUENCE  "phones_id_sequence";
ALTER TABLE "phones" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"phones_id_sequence"');
DROP SEQUENCE IF EXISTS "categories_id_sequence";
CREATE SEQUENCE  "categories_id_sequence";
ALTER TABLE "categories" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"categories_id_sequence"');
DROP SEQUENCE IF EXISTS "orders_id_sequence";
CREATE SEQUENCE  "orders_id_sequence";
ALTER TABLE "orders" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"orders_id_sequence"');
DROP SEQUENCE IF EXISTS "movimentations_id_sequence";
CREATE SEQUENCE  "movimentations_id_sequence";
ALTER TABLE "movimentations" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"movimentations_id_sequence"');
